---
#################
###  Redmine  ###
#################
REDMINE_DOCKER_TAG: latest
REDMINE_DOCKER_NETWORK_NAME: '{{ DOCKER_NETWORK_NAME }}'
REDMINE_DOCKER_HTTP_PORT: 8080

REDMINE_TIMEZONE: Etc/UTC

REDMINE_DB_HOST: 192.168.88.128
REDMINE_DB_PORT: 3306
REDMINE_DB_USERNAME: redmine
REDMINE_DB_PASSWORD: redmine_password
REDMINE_DB_DATABASE: redmine
REDMINE_DB_ENCODING: utf8mb4

REDMINE_SECRET_KEY_BASE: change_me_to_long_random_secret
REDMINE_LANG: en
