---
- name: Install and config NextCloud
  block:
    - name: Config NextCloud DataBase
      block:
        - name: Create NextCloud DB
          mysql_db:
            name: '{{ NEXTCLOUD_DB_NAME }}'
            collation: utf8mb4_general_ci
            encoding: utf8mb4
            login_unix_socket: /var/run/mysqld/mysqld.sock
            state: present
          notify: Restart MariaDB

        - name: Create NextCloud DB user
          mysql_user:
            name: '{{ NEXTCLOUD_DB_USER }}'
            password: '{{ NEXTCLOUD_DB_PASSWORD }}'
            host: '{{ NEXTCLOUD_DB_ACCESS_SUBNET }}'
            priv: '{{ NEXTCLOUD_DB_NAME }}.*:ALL,GRANT'
            login_unix_socket: /var/run/mysqld/mysqld.sock
            state: present
          notify: Restart MariaDB
          no_log: true
      become: true

    - name: Apply and run NextCloud Docker Compose
      block:
        - name: Create directory
          file:
            path: /opt/nextcloud_docker/
            state: directory
            owner: '{{ USERNAME }}'
            mode: 0640

        - name: Apply Docker Compose template
          template:
            src: docker_compose.yml.j2
            dest: /opt/nextcloud_docker/docker-compose.yml
            owner: '{{ USERNAME }}'
            mode: 0640

        - name: Run Docker Compose
          command: docker compose up -d
          args:
            chdir: /opt/nextcloud_docker/
      become: true

    - name: Apply NextCloud nginx config
      block:
        - name: Copy NextCloud nginx config
          template:
            src: nextcloud_nginx.conf.j2
            dest: /etc/nginx/sites-available/nextcloud.conf
            mode: 0640
          notify: Restart nginx

        - name: Enable NextCloud nginx config
          file:
            src: /etc/nginx/sites-available/nextcloud.conf
            dest: /etc/nginx/sites-enabled/nextcloud.conf
            state: link
          notify: Restart nginx
      become: true

  tags: docker_nextcloud
