---
- name: Install and config webserver
  block:
    - name: Install nginx
      apt:
        name: nginx
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Config UFW
      block:
        - name: Check UFW installed
          shell:
            cmd: |
              ufw --version >/dev/null
              echo "$?"
          register: ufw_return
        - name: Allow HTTP(S)
          ufw:
            rule: allow
            src: '{{ SERVER_SUBNET }}'
            port: '{{ item }}'
            state: reloaded
          with_items:
            - 80
            - 443
          when: ufw_return.stdout=="0"
      tags: firewall

    - name: Make webapge dir
      file:
        path: /var/www/srv
        state: directory
        mode: 0755

    - name: Deploy homepage
      template:
        src: index.html
        dest: /var/www/srv/index.html
        mode: 0644

    - name: Make services dir
      file:
        path: /etc/nginx/services.d
        state: directory
        mode: 0755

    - name: Copy ssl cert
      copy:
        src: '{{ SSL_CERT_PATH }}'
        dest: /etc/ssl/certs/{{ SSL_CERT_NAME }}
        mode: 0444

    - name: Copy ssl key
      copy:
        src: '{{ SSL_KEY_PATH }}'
        dest: /etc/ssl/private/{{ SSL_KEY_NAME }}
        mode: 0444

    - name: Copy dh group
      copy:
        src: '{{ DH_PATH }}'
        dest: /etc/nginx/{{ DH_NAME }}
        mode: 0444

    - name: Apply ssl config
      template:
        src: ssl-params.j2
        dest: /etc/nginx/snippets/ssl-params.conf
        mode: 0644

    - name: Apply nginx config
      template:
        src: nginx_default.j2
        dest: /etc/nginx/sites-available/default
        mode: 0644

    - name: Enable ngixn config
      file:
        src: /etc/nginx/sites-available/default
        dest: /etc/nginx/sites-enabled/default
        state: link
        mode: 0644
      notify: Restart nginx

  become: true
  tags: nginx
