---
NEXTCLOUD_DOMAIN: cloud.{{ DOMAIN_NAME }}
NEXTCLOUD_DOCKER_VERSION: stable
NEXTCLOUD_PORT: 9001
NEXTCLOUD_PATH: /var/www/html/nextcloud
NEXTCLOUD_MAX_FILE_SIZE: 4G
NEXTCLOUD_DB_NAME: nextclouddb
NEXTCLOUD_DB_USER: nextclouduser
NEXTCLOUD_DB_PASSWORD: qwerty1234!
