---
- name: Install and config transmission
  block:
    - name: Install transmission-daemon
      apt:
        name: transmission-daemon
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Stop transmission services
      service:
        name: transmission-daemon
        state: stopped

    - name: Apply nginx config
      template:
        src: nginx_transmission.j2
        dest: /etc/nginx/services.d/nginx_transmission.conf
        mode: 0644
      notify: Restart nginx

    - name: Make transmission dir
      file:
        path: /mnt/{{ DISK_LABEL }}/transmission/{{ item }}
        state: directory
        recurse: true
        mode: 0775
        owner: '{{ TRANSMISSION_SYSTEM_GROUP }}'
        group: '{{ SHARE_DISK_GROUP }}'
      with_items:
        - downloads
        - process

    - name: Apply transmission config
      template:
        src: transmission_settings.j2
        dest: /etc/transmission-daemon/settings.json
        mode: 0600
      notify: Start transmission

  become: true
  tags: transmission
