---
- name: base_config_role
  src: git+https://github.com/ggragham/base_config_role.git
  scm: git
  version: master

- name: hardening_ansible_role
  src: git+https://github.com/ggragham/hardening_ansible_role.git
  scm: git
  version: master
