---
##################
###  Jellyfin  ###
##################
JELLYFIN_INSTALL_METHOD: docker  # Installation method for Jellyfin (docker or proxmox).
JELLYFIN_DOCKER_VERSION: latest  # Jellyfin Docker image version.
JELLYFIN_DOCKER_HTTP_PORT: 8096  # Jellyfin WebUI HTTP port.
JELLYFIN_DOCKER_DISCOVERY_PORT: 7359  # Jellyfin Client Discrovery port (set to false to disable, or specify a port number).
JELLYFIN_DOCKER_USE_NGINX: false  # Toggle to use Nginx as a reverse proxy for Jellyfin.
JELLYFIN_DOCKER_NGINX_REDIRECT_HTTPS: false  # Redirect HTTP to HTTPS in Nginx.
JELLYFIN_DOCKER_MEDIA_PATH:  # Mapping of media directories to Jellyfin container.
  - name: anime  # Name for the media path.
    source: /mnt/anime  # Host source directory for media.
    target: /anime  # Container target directory for media.
    read_only: true  # If true, media can’t be modified from the container.
  - name: shows
    source: /mnt/shows
    target: /shows
    read_only: false

JELLYFIN_DOMAIN: jellyfin.{{ DOMAIN_NAME }}  # Domain name for the Jellyfin service.

PROXMOX_HOSTNAME: example.com  # Proxmox VE instance hostname.
PROXMOX_NODE: srv-01  # Proxmox node name where the container runs.
PROXMOX_API_HOST: pve.example.com  # Proxmox API hostname or IP.
PROXMOX_API_PORT: 8006  # Proxmox API port.
PROXMOX_API_USER: root@pam  # Proxmox API username.
PROXMOX_API_PASSWORD: foobar123  # Proxmox API password.
PROXMOX_CONTAINER_VMID: '100'  # Numeric VMID of the LXC container.
PROXMOX_VALIDATE_SSL: false  # Whether to verify the API TLS certificate.

PROXMOX_MOUNT_VOLUMES:  # Bind mounts from host into the container.
  - id: mp0  # LXC mount slot.
    host_path: /opt/media  # Absolute path on the Proxmox node.
    mountpoint: /mnt/media  # Target path inside the container.
  - id: mp1
    host_path: /opt/data
    mountpoint: /mnt/data
