---
############
#  Docker  #
############

DOCKER_NETWORK_NAME: homelab_network  # Name of the Docker network.
DOCKER_BRIDGE_NAME: homelab_bridge  # Name of the bridge interface for the Docker network.
