---
# Monitoring Docker container names.
MONITORING_GRAFANA_CONTAINER_NAME: grafana_container
MONITORING_PROMETHEUS_CONTAINER_NAME: prometheus_container
MONITORING_ALERTMANAGER_CONTAINER_NAME: alertmanager_container
MONITORING_BLACKBOX_EXPORTER_CONTAINER_NAME: blackbox_exporter_container

# Monitoring Docker service names.
MONITORING_GRAFANA_SERVICE_NAME: grafana
MONITORING_PROMETHEUS_SERVICE_NAME: prometheus
MONITORING_ALERTMANAGER_SERVICE_NAME: alertmanager
MONITORING_BLACKBOX_EXPORTER_SERVICE_NAME: blackbox_exporter

MONITORING_DOCKER_PATH: /opt/monitoring_docker  # Monitoring Docker installation path.

# Monitoring configuration paths.
MONITORING_PROMETHEUS_CONFIG_PATH: '{{ MONITORING_DOCKER_PATH }}/prometheus'
MONITORING_PROMETHEUS_TARGETS_PATH: '{{ MONITORING_PROMETHEUS_CONFIG_PATH }}/targets'
MONITORING_ALERTMANAGER_CONFIG_PATH: '{{ MONITORING_DOCKER_PATH }}/alertmanager'
MONITORING_BLACKBOX_CONFIG_PATH: '{{ MONITORING_DOCKER_PATH }}/blackbox'

# Grafana configuration paths.
MONITORING_GRAFANA_PATH: '{{ MONITORING_DOCKER_PATH }}/grafana'
MONITORING_GRAFANA_DATA_PATH: '{{ MONITORING_GRAFANA_PATH }}/data'
MONITORING_GRAFANA_CONFIG_PATH: '{{ MONITORING_GRAFANA_PATH }}/config'
MONITORING_GRAFANA_DATASOURCES_PATH: '{{ MONITORING_GRAFANA_CONFIG_PATH }}/provisioning/datasources'

MONITORING_GRAFANA_UID: 472  # Grafana user ID.
