---
# SSH
SSH_PORT: 22  # Set ssh port for firewall
SERVER_SUBNET: 192.168.1.0/24

# OpenVPN
OPENVPN_ENABLED: false
OPENVPN_CONFIG_PATH: '{{ ASSETS_PATH }}/client.ovpn'
OPENVPN_PORT: 1194
VPN_SUBNET: 10.8.0.0/24

# External Disk
EXT_DISK_ENABLED: true  # Enables or disables external disk mounting
DISK_LABEL: disk  # External disk label
DISK_ENCRYPTED: false  # Disk encryption status
DISK_KEYFILE: keyfile.pem  # Encryption key file name
DISK_KEYFILE_PATH: '{{ ASSETS_PATH }}/{{ DISK_KEYFILE }}'  # Path to encryption key file

# SFTP
SHARING_ENABLED: false
SHARE_DISK_GROUP: disksharegroup  # Group name for sftp access to ext drive
SHARE_DISK_USER: diskshareuser  # User name for sftp access to an ext drive
SHARE_PUBLIC_USER: publicshareuser  # User name for sftp access to public dir on ext drive
