---
- name: Start Gitea
  service:
    name: gitea
    state: started
  become: true
- name: Restart MariaDB
  service:
    name: mariadb
    state: restarted
  become: true
- name: Restart nginx
  service:
    name: nginx
    state: restarted
  become: true
