---
- name: Install and config NextCloud
  block:
    # - name: Config NextCloud DataBase
    #   block:
    #     - name: Create NextCloud DB
    #       mysql_db:
    #         name: '{{ NEXTCLOUD_DB_NAME }}'
    #         collation: utf8mb4_general_ci
    #         encoding: utf8mb4
    #         login_unix_socket: /var/run/mysqld/mysqld.sock
    #         state: present
    #       notify: Restart MariaDB

    #     - name: Create NextCloud DB user
    #       mysql_user:
    #         name: '{{ NEXTCLOUD_DB_USER }}'
    #         password: '{{ NEXTCLOUD_DB_PASSWORD }}'
    #         host: '{{ NEXTCLOUD_DB_ACCESS_SUBNET }}'
    #         priv: '{{ NEXTCLOUD_DB_NAME }}.*:ALL,GRANT'
    #         login_unix_socket: /var/run/mysqld/mysqld.sock
    #         state: present
    #       notify: Restart MariaDB
    #       no_log: true

    #     - name: Flush handlers
    #       meta: flush_handlers

    #   become: true

    - name: NextCloud containerized install
      block:
        - name: Check Docker existence
          block:
            - name: Check Docker binary existence
              stat:
                path: /usr/bin/docker
              register: docker_installed
            - name: Show error if Docker not isntalled
              fail:
                msg: Docker is not installed
              when: not docker_installed.stat.exists

        - name: Create Nextcloud Docker directory
          file:
            path: '{{ NEXTCLOUD_DOCKER_PATH }}'
            state: directory
            owner: '{{ USERNAME }}'
            mode: 0755

        - name: Apply NextCloud Config
          template:
            src: '{{ config }}.j2'
            dest: '{{ NEXTCLOUD_DOCKER_PATH }}/{{ config }}'
            mode: 0640
          loop_control:
            loop_var: config
          loop:
            - 000-default.conf
            - ports.conf

        - name: Apply NextCloud Docker Compose template
          template:
            src: docker_compose.yml.j2
            dest: '{{ NEXTCLOUD_DOCKER_PATH }}/docker-compose.yml'
            owner: '{{ USERNAME }}'
            mode: 0644

        - name: Copy NextCloud nginx config
          template:
            src: nextcloud_nginx.conf.j2
            dest: '{{ NGINX_SITES_ENABLED_PATH }}/nextcloud.conf'
            owner: '{{ NGINX_USER }}'
            mode: 0644
          when: NEXTCLOUD_USE_NGINX

        - name: Deploy Nextcloud background jobs service and timer
          template:
            src: '{{ item }}.j2'
            dest: /etc/systemd/system/{{ item }}
            owner: root
            group: root
            mode: '0644'
          loop:
            - nextcloud_background_job.service
            - nextcloud_background_job.timer

      become: true

    - name: Start dockerized NextCloud service
      block:
        - name: Run Docker Compose
          shell: docker compose down && docker compose up -d
          args:
            chdir: '{{ NEXTCLOUD_DOCKER_PATH }}'

        - name: Restart Nginx
          shell: docker compose down && docker compose up -d
          args:
            chdir: '{{ NGINX_DOCKER_PATH }}'
          when: NEXTCLOUD_USE_NGINX

    - name: Enable background jobs service
      block:
        - name: Reload systemd daemon
          systemd:
            daemon_reload: true

        - name: Enable and start Nextcloud cron job timer
          systemd:
            name: nextcloud_background_job.timer
            state: started
            enabled: true
      become: true

  when: NEXTCLOUD_DOCKERIZED
  tags: nextcloud
