---
TRANSMISSION_SYSTEM_USER: debian-transmission  # System group to set directory permissions
TRANSMISSION_SYSTEM_USER_ID: 1105
TRANSMISSION_DOWNLOAD_PATH: '{{ TRANSMISSION_DATA_PATH }}/downloads'
TRANSMISSION_PROCESS_PATH: '{{ TRANSMISSION_DATA_PATH }}/process'
TRANSMISSION_WATCH_PATH: '{{ TRANSMISSION_DATA_PATH }}/watch'
TRANSMISSION_CONFIG_PATH: /etc/transmission
