---
TRANSMISSION_SYSTEM_USER: debian-transmission  # System group to set directory permissions
TRANSMISSION_SYSTEM_USER_ID: 1105
TRANSMISSION_DOWNLOAD_PATH: '{{ TRANSMISSION_DATA_PATH }}/downloads'
TRANSMISSION_PROCESS_PATH: '{{ TRANSMISSION_DATA_PATH }}/process'
TRANSMISSION_WATCH_PATH: '{{ TRANSMISSION_DATA_PATH }}/watch'
TRANSMISSION_DOCKER_PATH: /opt/transmission_docker
TRANSMISSION_CONFIG_PATH: "{{ (TRANSMISSION_DOCKERIZED) | ternary(TRANSMISSION_DOCKER_PATH + '/config', '/etc/transmission-daemon') }}"
TRANSMISSION_DOCKER_SERVICE_NAME: transmission
TRANSMISSION_CONTAINER_NAME: transmission_container
