---
- name: Install and config MariaDB
  block:
    - name: Install MariaDB
      apt:
        name: [mariadb-server, python3-pymysql]
        state: latest
        update_cache: true
        install_recommends: false
      when: ansible_os_family=="Debian"

    - name: Remove MariaDB anonymous users
      mysql_user:
        name: ''
        host_all: true
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: absent
      notify: Restart MariaDB

    - name: Remove MariaDB test database
      mysql_db:
        db: test
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: absent
      notify: Restart MariaDB

    - name: Secure MariaDB root user
      mysql_user:
        user: root
        host: '{{ item }}'
        login_unix_socket: /var/run/mysqld/mysqld.sock
      with_items: ['::1', 127.0.0.1, localhost, '{{ ansible_fqdn }}']
      no_log: true
      notify: Restart MariaDB

  become: true
  tags: mariadb
