---
- name: Install and config transmission
  block:
    - name: Install transmission-daemon
      apt:
        name: transmission-daemon
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Stop transmission services
      service:
        name: transmission-daemon
        state: stopped

    - name: Apply Transmission nginx config
      block:
        - name: Copy Transmission nginx config
          template:
            src: nginx_transmission.j2
            dest: /etc/nginx/sites-available/transmission.conf
            mode: 0640

        - name: Enable Transmission nginx config
          file:
            src: /etc/nginx/sites-available/transmission.conf
            dest: /etc/nginx/sites-enabled/transmission.conf
            state: link

    - name: Make transmission dir
      file:
        path: /mnt/{{ DISK_LABEL }}/transmission/{{ item }}
        state: directory
        recurse: true
        mode: 0775
        owner: '{{ TRANSMISSION_SYSTEM_GROUP }}'
        group: '{{ SHARE_DISK_GROUP }}'
      with_items:
        - downloads
        - process

    - name: Apply transmission config
      template:
        src: transmission_settings.j2
        dest: /etc/transmission-daemon/settings.json
        mode: 0600
      notify: Start transmission

  become: true
  tags: transmission
