---
- name: Add {{ GITEA_USER }} to docker group
  user:
    name: '{{ GITEA_USER }}'
    groups: docker
    append: true
  become: true

- name: Create directory
  file:
    path: '{{ GITEA_DOCKER_PATH }}'
    state: directory
    owner: '{{ GITEA_USER }}'
    group: root
    mode: 0775
  become: true

- name: Apply Docker Compose template
  template:
    src: docker_compose.yml.j2
    dest: '{{ GITEA_DOCKER_PATH }}/docker-compose.yml'
    owner: '{{ GITEA_USER }}'
    group: root
    mode: 0644
  become: true

- name: Install and configure actrunner
  block:
    - name: Create act_runner data dir
      file:
        path: '{{ ACT_DATA_PATH }}'
        owner: '{{ GITEA_USER }}'
        group: '{{ GITEA_USER }}'
        state: directory
        mode: 0775
      become: true

    - name: Apply act_runner config
      template:
        src: act_config.yml.j2
        dest: '{{ GITEA_DOCKER_PATH }}/act_config.yml'
        owner: '{{ GITEA_USER }}'
        group: root
        mode: 0644
      become: true

    - name: Start ActRunner
      community.docker.docker_compose_v2:
        project_src: '{{ GITEA_DOCKER_PATH }}'
        state: present
        recreate: always
        remove_orphans: true
