---
- name: Add {{ GITEA_USER }} to docker group
  user:
    name: '{{ GITEA_USER }}'
    groups: docker
    append: true
  become: true

- name: Create directory
  file:
    path: '{{ GITEA_DOCKER_PATH }}'
    state: directory
    owner: '{{ GITEA_USER }}'
    group: root
    mode: 0775
  become: true

- name: Apply Docker Compose template
  template:
    src: docker_compose.yml.j2
    dest: '{{ GITEA_DOCKER_PATH }}/docker-compose.yml'
    owner: '{{ GITEA_USER }}'
    group: root
    mode: 0644
  become: true

- name: Remove runner
  file:
    path: '{{ ACT_DATA_PATH }}/.runner'
    state: absent
  when: ACTRUNNER_REREGISTER_RUNNER
  become: true

- name: Install and configure actrunner
  block:
    - name: Create act_runner data dir
      file:
        path: '{{ ACT_DATA_PATH }}'
        owner: '{{ GITEA_USER }}'
        group: '{{ GITEA_USER }}'
        state: directory
        mode: 0775
      become: true

    - name: Apply act_runner config
      template:
        src: act_config.yml.j2
        dest: '{{ GITEA_DOCKER_PATH }}/act_config.yml'
        owner: '{{ GITEA_USER }}'
        group: root
        mode: 0644
      become: true

    - name: Run Docker Compose
      shell: docker compose down && docker compose up -d {{ ACT_DOCKER_SERVICE_NAME }}
      args:
        chdir: '{{ GITEA_DOCKER_PATH }}'
