---
- name: Gitea Actions
  block:
    - name: Add {{ GITEA_USER }} to docker group
      user:
        name: '{{ GITEA_USER }}'
        groups: docker
        append: true

    - name: Create directory
      file:
        path: '{{ GITEA_DOCKER_PATH }}'
        state: directory
        owner: '{{ GITEA_USER }}'
        group: root
        mode: 0775

    - name: Apply Docker Compose template
      template:
        src: docker_compose.yml.j2
        dest: '{{ GITEA_DOCKER_PATH }}/docker-compose.yml'
        owner: '{{ GITEA_USER }}'
        group: root
        mode: 0644

    - name: Init Docker Compose
      shell: docker compose up -d --no-deps --no-start
      args:
        chdir: '{{ GITEA_DOCKER_PATH }}'

    - name: Remove runner
      file:
        path: '{{ ACT_DATA_PATH }}/.runner'
        state: absent
      when: ACT_REREGISTER_RUNNER
      tags: act_runner

    - name: Check runner existence
      stat:
        path: '{{ ACT_DATA_PATH }}/.runner'
      register: runner_exist
      tags: act_runner

    - name: Install and configure actrunner
      block:
        - name: Create act_runner data dir
          file:
            path: '{{ ACT_DATA_PATH }}'
            owner: '{{ GITEA_USER }}'
            group: '{{ GITEA_USER }}'
            state: directory
            mode: 0775

        - name: Apply act_runner config
          template:
            src: act_config.yml.j2
            dest: '{{ GITEA_DOCKER_PATH }}/act_config.yml'
            owner: '{{ GITEA_USER }}'
            group: root
            mode: 0644

        - name: Create .runner file
          file:
            path: '{{ ACT_DATA_PATH}}/.runner'
            state: touch
            mode: '0644'

        - name: Register runner
          shell: >
            docker run
            -v {{ ACT_DATA_PATH }}/.runner:/.runner
            -v ./act_config.yml:/config.yml
            -v /var/run/docker.sock:/var/run/docker.sock
            {% if GITEA_DEPLOY and ACTRUNNER_DEPLOY %}--network={{ GITEA_DOCKER_SERVICE_NAME }}_docker_{{ ACT_DOCKER_NETWORK }}{% endif %}
            --entrypoint=""
            --rm gitea/act_runner:latest
            act_runner register
            --no-interactive
            --instance http://{{ GITEA_IP }}:{{ GITEA_PORT }}
            --token {{ runner_token }}
          args:
            chdir: '{{ GITEA_DOCKER_PATH }}'

        - name: Run Docker Compose
          shell: docker compose down && docker compose up -d {{ ACT_DOCKER_SERVICE_NAME }}
          args:
            chdir: '{{ GITEA_DOCKER_PATH }}'

      when: GITEA_DOCKERIZED and (not runner_exist.stat.exists or runner_exist.stat.size == 0)

  become: true
  tags: gitea
