---
- name: Set backup filename
  set_fact:
    gitea_dump_name: gitea-dump-{{ ansible_date_time.epoch }}.zip

- name: Backup Gitea data (Bare Metal)
  command: >
    {{ GITEA_PATH }}/gitea
    dump --file {{ gitea_dump_name }}
    -c {{ GITEA_CONFIG_PATH }}/app.ini
  args:
    chdir: /tmp
  become: true
  become_user: '{{ GITEA_USER}}'
  when: not GITEA_DOCKERIZED

- name: Backup Gitea data (Docker)
  block:
    - name: Backup Gitea data (Docker)
      community.docker.docker_compose_v2_exec:
        project_src: '{{ GITEA_DOCKER_PATH }}'
        service: '{{ GITEA_DOCKER_SERVICE_NAME }}'
        chdir: /tmp
        command: >
          /app/gitea/gitea dump
          --file {{ gitea_dump_name }}
          -c /etc/gitea/app.ini

    - name: Copy Gitea backup from docker to gitea host
      command: docker cp {{ GITEA_CONTAINER_NAME }}:/tmp/{{ gitea_dump_name }} /tmp

- name: Fetch Gitea backup
  fetch:
    src: /tmp/{{ gitea_dump_name }}
    dest: ./assets/
    flat: true
