---
- name: Set Gitea Restore vars
  set_fact:
    gitea_dump_file: /tmp/{{ gitea_dump_name }}
    gitea_db_dump_file: /tmp/gitea_dump/gitea-db.sql
    gitea_extract_dir: /tmp/gitea_dump
    gitea_etc_dir: '{{ GITEA_CONFIG_PATH }}'
    gitea_data_dir: '{{ GITEA_DATA_PATH }}'
    gitea_repos_dir: '{{ GITEA_DATA_PATH }}/data/repositories'

- name: Copy Gitea dump to host
  copy:
    src: ./assets/{{ gitea_dump_name }}
    dest: '{{ gitea_dump_file }}'
    owner: '{{ GITEA_USER }}'
    group: root
    mode: '0644'
  become: true

- name: Ensure unzip is present
  package:
    name: unzip
    state: present
  become: true

- name: Ensure clean Gitea extract dir
  file:
    path: '{{ gitea_extract_dir }}'
    state: absent
  become: true

- name: Re-create Gitea extract dir
  file:
    path: '{{ gitea_extract_dir }}'
    state: directory
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0755'
  become: true

- name: Extract Gitea dump
  unarchive:
    src: '{{ gitea_dump_file }}'
    dest: '{{ gitea_extract_dir }}'
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0755'
    remote_src: true
  become: true

- name: Stop Gitea
  block:
    - name: Stop Gitea (Bare Metal)
      service:
        name: gitea
        state: stopped
      become: true
      when: not GITEA_DOCKERIZED

    - name: Stop Gitea (Docker)
      community.docker.docker_compose_v2:
        project_src: '{{ GITEA_DOCKER_PATH }}'
        services: '{{ GITEA_DOCKER_SERVICE_NAME }}'
        state: absent
      when: GITEA_DOCKERIZED

- name: Ensure Gitea target dirs exist
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0755'
  loop:
    - '{{ gitea_etc_dir }}'
    - '{{ gitea_data_dir }}'
    - '{{ gitea_repos_dir }}'
  become: true

- name: Restore Gitea config
  copy:
    src: '{{ gitea_extract_dir }}/app.ini'
    dest: '{{ gitea_etc_dir }}/app.ini'
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0600'
    remote_src: true
  become: true

- name: Restore Gitea data dir
  copy:
    src: '{{ gitea_extract_dir }}/data/'
    dest: '{{ gitea_data_dir }}'
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0755'
    remote_src: true
  become: true

- name: Restore Gitea repos
  copy:
    src: '{{ gitea_extract_dir }}/repos/'
    dest: '{{ gitea_repos_dir }}/'
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0755'
    remote_src: true
  become: true

- name: Restore MariaDB data
  block:
    - name: Restore MeriaDB (Docker)
      block:
        - name: Copy Gitea SQL dump to MariaDB container (Docker)
          community.docker.docker_container_copy_into:
            container: '{{ GITEA_DB_CONTAINER_NAME }}'
            path: '{{ gitea_db_dump_file }}'
            container_path: /tmp/gitea-db.sql

        - name: Drop & recreate Gitea database {{ GITEA_DB_NAME }} (Docker)
          community.docker.docker_compose_v2_exec:
            project_src: '{{ GITEA_DOCKER_PATH }}'
            service: '{{ GITEA_DOCKER_DB_SERVICE_NAME }}'
            command: >
              sh -lc "mariadb -uroot -p'{{ GITEA_DB_ROOT_PASSWORD }}' -e
              \"DROP DATABASE IF EXISTS \`{{ GITEA_DB_NAME }}\`;
                CREATE DATABASE \`{{ GITEA_DB_NAME }}\`
                CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci;\""
          no_log: true

        - name: Restore Gitea MariaDB data (Docker)
          community.docker.docker_compose_v2_exec:
            project_src: '{{ GITEA_DOCKER_PATH }}'
            service: '{{ GITEA_DOCKER_DB_SERVICE_NAME }}'
            command: >
              sh -lc "mariadb -u{{ GITEA_DB_USER }} -p'{{ GITEA_DB_PASSWORD }}' {{ GITEA_DB_NAME }}
              < /tmp/gitea-db.sql"
          no_log: true

      when:
        - GITEA_DOCKERIZED
        - GITEA_DB_DEPLOY

    - name: Restore MariaDB (Bare Metal)
      block:
        - name: Install MariaDB dependencies (Bare Metal)
          block:
            - name: Install MariaDB dependencies on Debian-based system
              apt:
                name:
                  - python3-pymysql
                  - mariadb-client
                state: present
                update_cache: true
              when: ansible_os_family == 'Debian'
              become: true

            - name: Install MariaDB dependencies on RHEL-based system
              dnf:
                name:
                  - python3-PyMySQL
                  - mariadb
                state: latest
                update_cache: true
                install_weak_deps: false
              when: ansible_os_family == "RedHat"
              become: true

        - name: Drop Gitea database (Bare Metal)
          mysql_db:
            name: '{{ GITEA_DB_NAME }}'
            login_host: '{{ GITEA_DB_HOST }}'
            login_port: '{{ GITEA_DB_PORT | default(3306) }}'
            login_user: '{{ GITEA_DB_ROOT_USER | default(root) }}'
            login_password: '{{ GITEA_DB_ROOT_PASSWORD }}'
            state: absent
          no_log: true

        - name: Create Gitea database (Bare Metal)
          mysql_db:
            name: '{{ GITEA_DB_NAME }}'
            login_host: '{{ GITEA_DB_HOST }}'
            login_port: '{{ GITEA_DB_PORT | default(3306) }}'
            login_user: '{{ GITEA_DB_ROOT_USER | default(root) }}'
            login_password: '{{ GITEA_DB_ROOT_PASSWORD }}'
            encoding: utf8mb4
            collation: utf8mb4_unicode_ci
            state: present
          no_log: true

        - name: Restore Gitea MariaDB data (Bate Metal)
          mysql_db:
            name: '{{ GITEA_DB_NAME }}'
            target: '{{ gitea_db_dump_file }}'
            login_host: '{{ GITEA_DB_HOST }}'
            login_port: '{{ GITEA_DB_PORT | default(3306) }}'
            login_user: '{{ GITEA_DB_USER }}'
            login_password: '{{ GITEA_DB_PASSWORD }}'
            state: import
          no_log: true

      when: not GITEA_DB_DEPLOY

  when: (gitea_restore_db | default(false)) | bool

- name: Start Gitea
  block:
    - name: Start Gitea (Bare Metal)
      service:
        name: gitea
        state: started
      become: true
      when: not GITEA_DOCKERIZED

    - name: Start Gitea (Docker)
      community.docker.docker_compose_v2:
        project_src: '{{ GITEA_DOCKER_PATH }}'
        services: '{{ GITEA_DOCKER_SERVICE_NAME }}'
        state: present
      when: GITEA_DOCKERIZED

- name: Regenerate Gitea hooks
  block:
    - name: Regenerate Gitea Hooks (Bare Metal)
      command: '{{ GITEA_PATH }}/gitea -c /etc/gitea/app.ini admin regenerate hooks'
      become: true
      become_user: '{{ GITEA_USER }}'
      when: not GITEA_DOCKERIZED

    - name: Regenerate Gitea Hooks (Docker)
      community.docker.docker_compose_v2_exec:
        project_src: '{{ GITEA_DOCKER_PATH }}'
        service: '{{ GITEA_DOCKER_SERVICE_NAME }}'
        command: /usr/local/bin/gitea -c /etc/gitea/app.ini admin regenerate hooks
      when: GITEA_DOCKERIZED
