---
- name: Install deps
  apt:
    name: [git, jq]
    state: latest
    update_cache: true
  when: ansible_os_family=="Debian"
  become: true

- name: Config Gitea DataBase
  block:
    - name: Create Gitea DB
      mysql_db:
        name: '{{ GITEA_DB_NAME }}'
        collation: utf8mb4_general_ci
        encoding: utf8mb4
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      notify: Restart MariaDB

    - name: Create Gitea DB user
      mysql_user:
        name: '{{ GITEA_DB_USER }}'
        password: '{{ GITEA_DB_PASSWORD }}'
        host: '{{ (GITEA_DOCKERIZED) | ternary(GITEA_DB_ACCESS_SUBNET, "localhost") }}'
        priv: '{{ GITEA_DB_NAME }}.*:ALL,GRANT'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      notify: Restart MariaDB
      no_log: true

    - name: Flush handlers
      meta: flush_handlers

- name: Create Gitea dir
  file:
    path: '{{ GITEA_PATH }}'
    state: directory
    owner: '{{ GITEA_USER }}'
    group: root
    mode: '0775'
  become: true

- name: Get Gitea latest version
  shell:
    cmd: curl -s "https://api.github.com/repos/go-gitea/gitea/releases/latest" | jq -r '.tag_name' 2>&1 | sed -e 's|.*-||' -e 's|^v||'
  register: gitea_latest_version
  become: true

- name: x86_64
  set_fact:
    gitea_arch: amd64
  when: ansible_architecture=="x86_64"

- name: armv7
  set_fact:
    gitea_arch: arm-6
  when: ansible_architecture=="armv7l"

- name: Get Gitea
  get_url:
    url: https://dl.gitea.com/gitea/{{ gitea_latest_version.stdout }}/gitea-{{ gitea_latest_version.stdout }}-linux-{{ gitea_arch }}
    dest: '{{ GITEA_PATH }}/gitea'
    checksum: sha256:https://dl.gitea.com/gitea/{{ gitea_latest_version.stdout }}/gitea-{{ gitea_latest_version.stdout }}-linux-{{ gitea_arch }}.sha256
    mode: '0755'
  become: true

- name: Apply Gitea Nginx config
  template:
    src: gitea_nginx.j2
    dest: '{{ NGINX_SITES_AVAILABLE_PATH }}/gitea.conf'
    mode: '0644'
  when: GITEA_USE_NGINX
  notify: Restart nginx
  become: true

- name: Enable Gitea Nginx config
  file:
    src: '{{ NGINX_SITES_AVAILABLE_PATH }}/gitea.conf'
    dest: '{{ NGINX_SITES_ENABLED_PATH }}/gitea.conf'
    state: link
    mode: '0644'
  when: GITEA_USE_NGINX
  notify: Restart nginx
  become: true

- name: Systemd config
  template:
    src: gitea_service.j2
    dest: /etc/systemd/system/gitea.service
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0644'
  notify: Restart gitea
  become: true

- name: Apply config
  template:
    src: gitea_config.j2
    dest: '{{ GITEA_CONFIG_PATH }}/app.ini'
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0600'
  notify: Restart gitea
  no_log: true
  become: true
