---
- name: Create Gitea data dirs
  file:
    path: '{{ item }}'
    state: directory
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0755'
    recurse: true
  with_items:
    - '{{ GITEA_CONFIG_PATH }}'
    - '{{ GITEA_DATA_PATH }}'
    - '{{ GITEA_DATA_PATH }}/data'
  become: true

- name: Create Gitea database dir
  file:
    path: '{{ GITEA_DB_PATH }}'
    state: directory
    owner: '{{ GITEA_USER }}'
    group: '{{ GITEA_USER }}'
    mode: '0755'
    recurse: true
  when: GITEA_DB_DEPLOY
  become: true

- name: Gitea bare metal install
  include_tasks: gitea_baremetal.yml
  when: not GITEA_DOCKERIZED

- name: Gitea docker install
  include_tasks: gitea_docker.yml
  when: GITEA_DOCKERIZED
