---
- name: Gitea
  block:
    - name: Install and configure Gitea
      include_tasks: gitea.yml

    - name: Gitea Health Check
      block:
        - name: Wait for service to start
          uri:
            url: http://{{ GITEA_DOMAIN }}/api/healthz
            method: GET
            status_code: 200
            validate_certs: false
          register: result
          until: (result.status is defined) and (result.status == 200)
          retries: 30
          delay: 10
        - name: Fail if service is not running
          fail:
            msg: Service did not start in time
          when: result.failed
      delegate_to: localhost
      become: false

    - name: Add admin user
      block:
        - shell: >
            {{ (GITEA_DOCKERIZED) | ternary('docker exec -i ' + GITEA_CONTAINER_NAME + ' /app/gitea/gitea',
            'sudo -u ' + GITEA_USER + GITEA_PATH + '/gitea') }}
            admin user create --username {{ GITEA_ADMIN_USER }}
            --admin --password {{ GITEA_ADMIN_PASSWORD }}
            --email {{ GITEA_ADMIN_EMAIL }}
            -c {{ (GITEA_DOCKERIZED) | ternary('/etc/gitea', GITEA_CONFIG_PATH) }}/app.ini
          # no_log: true
      rescue:
        - debug:
            msg: Sucksessfully failed
      tags: gitea_create_admin_user

    - name: Install Act Runner
      include_tasks: actrunner.yml

  become: true
  tags: gitea
