---
- name: Install and config Gitea
  block:
    - name: Install deps
      apt:
        name: [git, jq]
        state: latest
        update_cache: true
      when: ansible_os_family=="Debian"
    - name: Create Gitea system user
      user:
        name: '{{ GITEA_USER }}'
        comment: Git Version Control
        home: /home/{{ GITEA_USER }}
        shell: /bin/bash
        password_lock: true
    - name: Create Gitea DB
      mysql_db:
        name: '{{ GITEA_DB_NAME }}'
        collation: utf8mb4_general_ci
        encoding: utf8mb4
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      notify: Restart MariaDB
    - name: Create Gitea DB user
      mysql_user:
        name: '{{ GITEA_DB_USER }}'
        password: '{{ GITEA_DB_PASSWORD }}'
        priv: '{{ GITEA_DB_NAME }}.*:ALL,GRANT'
        login_unix_socket: /var/run/mysqld/mysqld.sock
        state: present
      notify: Restart MariaDB
      no_log: true
    - name: Create Gitea data dirs
      file:
        path: '{{ item }}'
        state: directory
        owner: '{{ GITEA_USER }}'
        group: '{{ GITEA_USER }}'
        mode: 0750
        recurse: true
      with_items:
        - '{{ GITEA_CONFIG_PATH }}'
        - '{{ GITEA_DATA_PATH }}'
        - '{{ GITEA_DATA_PATH }}/data'
        - '{{ GITEA_DATA_PATH }}/custom'
        - '{{ GITEA_DATA_PATH }}/log'
    - name: Create Gitea dir
      file:
        path: '{{ GITEA_PATH }}'
        state: directory
        owner: '{{ GITEA_USER }}'
        group: root
        mode: 0775
    - name: Get Gitea latest version
      shell:
        cmd: curl -s "https://api.github.com/repos/go-gitea/gitea/releases/latest"
          | jq -r '.tag_name' 2>&1 | sed -e 's|.*-||' -e 's|^v||'
      register: gitea_latest_version
    - name: x86_64
      set_fact:
        gitea_arch: amd64
      when: ansible_architecture=="x86_64"
    - name: armv7
      set_fact:
        gitea_arch: arm-6
      when: ansible_architecture=="armv7l"
    - name: Get Gitea
      get_url:
        url: https://dl.gitea.com/gitea/{{ gitea_latest_version.stdout }}/gitea-{{
          gitea_latest_version.stdout }}-linux-{{ gitea_arch }}
        dest: '{{ GITEA_PATH }}/gitea'
        checksum: sha256:https://dl.gitea.com/gitea/{{ gitea_latest_version.stdout }}/gitea-{{
          gitea_latest_version.stdout }}-linux-{{ gitea_arch }}.sha256
        mode: 0755
    - name: Systemd config
      template:
        src: gitea_service.j2
        dest: /etc/systemd/system/gitea.service
        owner: '{{ GITEA_USER }}'
        group: '{{ GITEA_USER }}'
        mode: 0640
    - name: Apply config
      template:
        src: gitea_config.j2
        dest: '{{ GITEA_CONFIG_PATH }}/app.ini'
        owner: '{{ GITEA_USER }}'
        group: '{{ GITEA_USER }}'
        mode: 0600
      no_log: true
      notify: Start Gitea
    - name: Nginx config
      template:
        src: gitea_nginx.j2
        dest: /etc/nginx/services.d/gitea.conf
        mode: 0640
      notify: Restart nginx
  become: true
