---
- name: Set distro_name
  set_fact:
    distro_name: >-
      {{ (
        'fedora' if ansible_distribution | lower == 'fedora'
        else 'centos' if ansible_distribution | lower in ['alma', 'almalinux', 'rocky', 'rockylinux']
        else ansible_distribution | lower
      ).strip() }}

- name: Add repo to {{ ansible_distribution }}
  yum_repository:
    name: docker
    description: docker repository
    baseurl: https://download.docker.com/linux/{{ distro_name }}/$releasever/$basearch/stable
    enabled: true
    gpgcheck: true
    gpgkey: https://download.docker.com/linux/{{ distro_name }}/gpg
  become: true

- name: Install docker to {{ ansible_distribution }}
  dnf:
    name:
      - docker-ce
      - docker-ce-cli
      - containerd.io
      - docker-buildx-plugin
      - docker-compose-plugin
    state: latest
    update_cache: true
    install_weak_deps: false
  become: true
