---
- name: Install iptables
  block:
    - name: Install iptables to Debian
      apt:
        name: iptables
        state: latest
        update_cache: true
      when: ansible_os_family == 'Debian'
  become: true

- name: Apply iptables config
  block:
    - name: Create iptables dir struct
      file:
        path: '{{ IPTABLES_RULES_PATH_DEST }}'
        state: directory
        mode: 0700

    - name: Apply base iptables systemd service
      template:
        src: '{{ IPTABLES_BASE_RULES_NAME }}.service.j2'
        dest: '{{ SYSTEMD_SERVICES_PATH }}/{{ IPTABLES_BASE_RULES_NAME }}.service'
        mode: 0500

    - name: Apply base iptables rules
      template:
        src: '{{ IPTABLES_BASE_RULES_NAME }}.sh.j2'
        dest: '{{ IPTABLES_RULES_PATH_DEST }}/{{ IPTABLES_BASE_RULES_NAME }}.sh'
        mode: 0500
      notify: Enable base iptables rules

  become: true
