---
- name: Base tasks
  block:
    - name: Prepare steps
      block:
        - name: Update deb-based system
          apt:
            name: '*'
            state: latest
            update_cache: true
          when: ansible_os_family == "Debian"

        - name: Install necessary packages
          apt:
            name:
              - bash-completion
              - curl
              # - duf
              - vim
            state: latest
            update_cache: true
          when: ansible_os_family == "Debian"
      become: true

    - include_tasks: firewall.yml

    - include_tasks: wireguard.yml
      when: WIREGUARD_ENABLED

    - include_tasks: storage.yml
      when: EXT_DISK_ENABLED

    - include_tasks: sftp.yml
      when: SFTP_ENABLE

  tags: base
