---
- name: Prepare steps
  block:
    - name: Update deb-based system
      apt:
        name: '*'
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"

    - name: Install necessary packages
      apt:
        name:
          - bash-completion
          - curl
          # - duf
          - vim
        state: latest
        update_cache: true
      when: ansible_os_family == "Debian"

  become: true
  tags: prepare

- include_tasks: firewall.yml
  tags: firewall

- include_tasks: wireguard.yml
  when: WIREGUARD_ENABLED
  tags: wireguard

- include_tasks: storage.yml
  when: EXT_DISK_ENABLED

# SFTP
- name: Configure SFTP file sharing
  block:
    - name: Make disk share group
      group:
        name: '{{ SHARE_DISK_GROUP }}'
        state: present

    - name: Make disk share user
      user:
        name: '{{ SHARE_DISK_USER }}'
        shell: /usr/sbin/nologin
        groups: '{{ SHARE_DISK_GROUP }}'

    - name: Make public share user
      user:
        name: '{{ SHARE_PUBLIC_USER }}'
        shell: /usr/sbin/nologin

    - name: Make dir for random files
      file:
        path: '{{ DISK_DATA_PATH }}/files'
        state: directory
        recurse: true
        mode: 0775
        owner: '{{ SHARE_DISK_USER }}'
        group: '{{ SHARE_DISK_GROUP }}'

    - name: Make dir for public user
      file:
        path: '{{ DISK_DATA_PATH }}/share'
        state: directory
        mode: 0755
        owner: root
        group: root

    - name: Make dir for public user
      file:
        path: '{{ DISK_DATA_PATH }}/share/files'
        state: directory
        mode: 0755
        owner: '{{ SHARE_PUBLIC_USER }}'
        group: '{{ SHARE_PUBLIC_USER }}'

    - name: Apply sftp config
      template:
        src: 05_sftp.j2
        dest: /etc/ssh/sshd_config.d/05_sftp.conf
        mode: 0600
      notify: Restart sshd

  when: SHARING_ENABLED|bool
  become: true
  tags: sftp
