---
# OpenVPN
- name: Config OpenVPN
  block:
    - name: Check openvpn config existence
      stat:
        path: '{{ OPENVPN_CONFIG_PATH }}'
      delegate_to: localhost
      register: ovpn_config_existence

    - name: Install and config OpenVPN
      block:
        - name: Install OpenVPN
          apt:
            name: openvpn
            state: latest
            update_cache: true
          when: ansible_os_family == "Debian"

        - name: Apply config
          copy:
            src: '{{ OPENVPN_CONFIG_PATH }}'
            dest: /etc/openvpn/client/client.conf
            mode: 0400

        - name: Config UFW
          block:
            - name: Allow SSH from VPN
              ufw:
                rule: allow
                src: '{{ VPN_SUBNET }}'
                port: '{{ SSH_PORT }}'
                proto: tcp
                state: enabled
            - name: Allow HTTP(S) from VPN
              ufw:
                rule: allow
                src: '{{ VPN_SUBNET }}'
                port: '{{ item }}'
                state: reloaded
              with_items:
                - 80
                - 443
            - name: Allow out from tun0
              ufw:
                rule: allow
                interface: tun0
                direction: out
                state: reloaded
            - name: Allow outgoing traffic
              ufw:
                rule: allow
                interface: '{{ NETWORK_INTERFACE }}'
                direction: out
                port: '{{ item }}'
                proto: udp
                state: reloaded
              with_items:
                - '{{ OPENVPN_PORT }}'
          tags: firewall

        - name: Start OpenVPN
          service:
            name: openvpn-client@client.service
            state: started
            enabled: true

      when: ovpn_config_existence.stat.exists
      become: true

  when: OPENVPN_ENABLED|bool
  tags: openvpn
