---
# WireGuard
- name: Config WireGuard
  block:
    - name: Check WireGuard config existence
      stat:
        path: '{{ WIREGUARD_CONFIG_PATH_SRC }}'
      delegate_to: localhost
      register: wg_config_existence

    - name: Install and config WireGuard
      block:
        - name: Install WireGuard tools
          apt:
            name:
              - wireguard-tools
              - resolvconf
            state: latest
            update_cache: true
            install_recommends: false
          when: ansible_os_family == "Debian"

        - name: Apply config
          copy:
            src: '{{ WIREGUARD_CONFIG_PATH_SRC }}'
            dest: '{{ WIREGUARD_CONFIG_PATH_DEST }}/{{ WIREGUARD_CONFIG_NAME }}.conf'
            mode: 0400

        - name: Start WireGuard
          service:
            name: wg-quick@{{ WIREGUARD_CONFIG_NAME }}
            state: started
            enabled: true

      when: wg_config_existence.stat.exists
      become: true

  when: WIREGUARD_ENABLED
  tags: wireguard
