---
REDMINE_SERVICE_NAME: redmine  # Redmine service name.
REDMINE_DOCKER_SERVICE_NAME: '{{ REDMINE_SERVICE_NAME }}'  # Redmine Docker service name.
REDMINE_DOCKER_CONTAINER_NAME: '{{ REDMINE_SERVICE_NAME }}_container'  # Redmine Docker container name.

REDMINE_DOCKER_PATH: /opt/redmine_docker  # Redmine Docker installation path.
REDMINE_DOCKER_DATA_PATH: '{{ REDMINE_DOCKER_PATH }}/data'  # Redmine Docker data path.
REDMINE_DOCKER_FILES_PATH: '{{ REDMINE_DOCKER_DATA_PATH }}/files'  # Redmine Docker files path.
REDMINE_DOCKER_PLUGINS_PATH: '{{ REDMINE_DOCKER_DATA_PATH }}/plugins'  # Redmine Docker plugins path.
REDMINE_DOCKER_THEMES_PATH: '{{ REDMINE_DOCKER_DATA_PATH }}/themes'  # Redmine Docker themes path.
