---
REDMINE_DOCKER_SERVICE_NAME: redmine
REDMINE_DOCKER_CONTAINER_NAME: '{{ REDMINE_DOCKER_SERVICE_NAME }}-container'
REDMINE_DOCKER_HOST_UID: 1000
REDMINE_DOCKER_HOST_GID: 1000
REDMINE_DOCKER_PATH: /opt/redmine_docker
REDMINE_DOCKER_DATA_PATH: '{{ REDMINE_DOCKER_PATH }}/data'
REDMINE_DOCKER_FILES_PATH: '{{ REDMINE_DOCKER_DATA_PATH }}/files'
REDMINE_DOCKER_PLUGINS_PATH: '{{ REDMINE_DOCKER_DATA_PATH }}/plugins'
REDMINE_DOCKER_THEMES_PATH: '{{ REDMINE_DOCKER_DATA_PATH }}/themes'
