---
################
###  PiHole  ###
################

PIHOLE_DOCKERIZED: true  # Pihole dockerized install toogle.
PIHOLE_DOCKER_VERSION: latest  # Pi-hole Docker image version.
PIHOLE_DOCKER_WEBSERVER_PORT: false  # Web server port exposure (false to disable or specify a port number).
PIHOLE_USE_NGINX: false  # Toggle to use Nginx as a reverse proxy for Pi-hole.

PIHOLE_DOMAIN: dns.{{ DOMAIN_NAME }}  # Domain name for the Pi-hole service.
PIHOLE_ADMIN_PASSWORD: foobar123  # Password used to login in Pi-hole WebUI.
PIHOLE_QUERY_LOGGING: 'true'  # Toggle query logging.
PIHOLE_CACHE_SIZE: 10000  # DNS cache size.
PIHOLE_WEBUI_BOXED_LAYOUT: boxed  # Web interface layout.
PIHOLE_WEBUI_THEME: default-dark  # Web interface theme.
PIHOLE_DNS_RECORDS:  # List of DNS records to be created in Pi-hole.
  - '{{ ansible_host }} {{ DOMAIN_NAME }}'
  - '{{ ansible_host }} {{ PIHOLE_DOMAIN }}'
  - 10.8.0.2 example.com
  - 10.8.0.3 link1.example.com
  - 10.8.0.4 link2.example.com
