---
- name: Pi-hole
  block:
    - name: Pi-hole bare metal install
      include_tasks: pihole_baremetal.yml
      when: not PIHOLE_DOCKERIZED

    - name: Pi-hole docker install
      include_tasks: pihole_docker.yml
      when: PIHOLE_DOCKERIZED

    - name: Set Pi-hole admin password
      shell: >
        {% if PIHOLE_DOCKERIZED %}
        {{ 'docker exec -it ' + PIHOLE_CONTAINER_NAME }}
        {% endif %}
        pihole admin password {{ PIHOLE_ADMIN_PASSWORD }}
      no_log: true
